# Generated by Django 4.2.13 on 2025-01-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('competence_1', models.IntegerField()),
                ('competence_2', models.IntegerField()),
                ('competence_3', models.IntegerField()),
                ('competence_4', models.IntegerField()),
                ('competence_5', models.IntegerField()),
            ],
        ),
    ]
